theme: minima
title: Hello World
author: Jay Palacio
email: jaypalacio@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Getting the basics of github pages. laying the groundwork for a portfolio page.

# social links
github_username:  devPalacio
show_excerpts: true # set to false to remove excerpts on the homepage
