theme: minima
title: Hello World
author: Jay Palacio
email: jaypalacio@gmail.com
description: > Getting the basics of github pages. laying the groundwork for a portfolio page. # this means to ignore newlines until "baseurl:"

# social links
github_username:  devPalacio
show_excerpts: true # set to false to remove excerpts on the homepage
